### ISSUE TITLE
waffle.io needs webhooks enabled for realtime updates

### ISSUE THREAD

**Issue by jasonkarns** [OiNutter/nodenv#19]
I created a waffle board (https://waffle.io/OiNutter/nodenv) for nodenv/node-build and various plugins. (To get a clear picture of open issues, etc across the ecosystem.)

We need an admin (@OiNutter) to enable webhooks for waffle.io on the repos.

**Comment by OiNutter** [comment]
Ok, let me know what I need to do, or give me a link to some docs on it.

**Comment by jasonkarns** [comment]
visit the waffle page: https://waffle.io/oinutter/nodenv and authenticate
with github. there should be a warning in the footer with a button to
create the hooks

**Comment by OiNutter** [comment]
Done, but I can't add hooks for the nodenv-update repo. @charlesbjohnson needs to do that.

**Comment by charlesbjohnson** [comment]
Wasn't able to get it setup with the existing board.

![screen shot 2015-09-01 at 10 19 32 am](https://cloud.githubusercontent.com/assets/4823640/9611170/113b1088-5093-11e5-8807-2dea1b0f7608.png)

But seemed to work fine separately, https://waffle.io/charlesbjohnson/nodenv-update.

**Comment by jasonkarns** [comment]
reopening since @charlesbjohnson's nodenv-update didn't configure correctly.

**Comment by jasonkarns** [comment]
I've submitted a help request to @waffleio

**Comment by charlesbjohnson** [comment]
I removed the old integration I had set up the first time which I think should just leave the settings @OiNutter had configured at the start.  Additionally, I'm not seeing any errors now and creating an issue from waffle.io seemed to work (thanks @marydavis).

I wonder if it would be worthwhile to just create a nodenv github org so that this kind of a thing isn't an issue.

**Comment by jasonkarns** [comment]
There is a nodenv org, originally created for wfarr's version. They've
added a few of us, but we haven't yet gone further in moving any repos.

**Comment by jasonkarns** [comment]
@marydavis I'm still seeing the error message :/

![image](https://cloud.githubusercontent.com/assets/119972/11247618/d3975346-8dea-11e5-9c64-6eff8f077023.png)

**Comment by marydavis** [comment]
@charlesbjohnson do you see the same error message on that screen? If so, what happens when you click the "Create Hooks" button?

**Comment by charlesbjohnson** [comment]
It looks like I don't have access the the project settings, actually.  I'm guessing @jasonkarns or @OiNutter, needs to grant me access?

<img width="599" alt="screen shot 2015-11-18 at 9 45 47 pm" src="https://cloud.githubusercontent.com/assets/4823640/11263272/08128f02-8e3e-11e5-89c3-c5101c55ed1e.png">

**Comment by marydavis** [comment]
@charlesbjohnson do you see the banner request on the main board view?

**Comment by charlesbjohnson** [comment]
Apologies for the delay. @marydavis I believe I saw that request the very first time I signed up.  I wasn't able to create the webhooks given the way @jasonkarns set them up (see the screenshot from September).  I was only to create webhooks for my repo when I created *my own* waffle.io board.

Even since having deleted that board, I don't see any other banner request.

<img width="1029" alt="screen shot 2015-12-19 at 11 39 17 pm" src="https://cloud.githubusercontent.com/assets/4823640/11917030/7fe26334-a6aa-11e5-9c34-afae56253872.png">

**Comment by homeyer** [comment]
Hello! I'm jumping in for @marydavis, I'm also on the Waffle team.

@jasonkarns or @OiNutter, can you add @charlesbjohnson as a collaborator to oinutter/nodenv?

Right now we're not prompting Charles to create the webhook because he doesn't have permissions to edit the root project (oinutter/nodenv).

**Comment by ashumz** [comment]
Hey @jasonkarns @OiNutter @charlesbjohnon, 

Were you able to add @charlesbjohnson to the primary repo (oinutter/nodenv)? Once this happens, he will be able to create the necessary webhooks for any person repositories. 

Let us know if we can help further or if you're good to go. 

Cheers,

Ashley

**Comment by jasonkarns** [comment]
@ashumz Thanks for following up. I'm going to close this for now, since we're in the process of migrating to a nodenv github org. Once that's done, we'll have the waffle board only include nodenv-org repos, which should eliminate any trouble with owner/maintainer permissions issues.
